name: Publish Docker image

on:
    push:
        tags:
            - '*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Image initial
        id: script
        run: |
          STARTUP_CMD=$(cat <<- EOF
          <<COMMENT
          ${{ vars.STARTUP_CMD }}
          COMMENT
          EOF
          )
          STARTUP_DEFAULT=$(cat <<- EOF
          <<COMMENT
          COMMENT
          EOF
          )
          if [[ "$STARTUP_CMD" != $STARTUP_DEFAULT ]]; then
          STARTUP_PATH=startup.sh
          touch $STARTUP_PATH
          echo -e "$STARTUP_CMD" | sed -e "1d" | sed -e "\$d" > $STARTUP_PATH
          echo -e "Image initialed"
          fi
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ secrets.DOCKER_USERNAME }}/${{ vars.NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          build-args: |
            ALPINE_VERSION=${{ vars.ALPINE_VERSION }}
            MAINTAINER=${{ vars.MAINTAINER }}
            PORT=${{ vars.PORT }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.NAME }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
